routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index')->name('home');

Route::resource('categories', 'CategoryController')
    ->parameters([
        'category' =>'[0-9]+'
    ]);

Route::resource('posts', 'PostController')
    ->parameters([
        'post' =>'[0-9]+'
    ]);

/*Route::resource('comments', 'CommentController')->onlu
    ->parameters([
        'comment' =>'[0-9]+'
    ]);*/

Route::resource('/posts/{post}/comments', 'CommentController')->only(['store', 'destroy']);

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <h2>All Categories: </h2>
        <div class="col-md-8 flex-div">
            @foreach ($categories as $category)

            <div class="card" style="width: 18rem;">
                <div class="card-body div-body">
                    <h5 class="card-title">{{$category->label}}</h5>
                    <a href="{{route('categories.show', $category->id)}}" class="card-link"><button type="button" class="btn btn-outline-success">See posts in this Category</button></a>
                </div>
            </div>
            @endforeach

        </div>
    </div>
</div>
@endsection