routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index')->name('home');

Route::resource('categories', 'CategoryController')
    ->parameters([
        'category' =>'[0-9]+'
    ]);

Route::resource('posts', 'PostController')
    ->parameters([
        'post' =>'[0-9]+'
    ]);

/*Route::resource('comments', 'CommentController')->onlu
    ->parameters([
        'comment' =>'[0-9]+'
    ]);*/

Route::resource('/posts/{post}/comments', 'CommentController')->only(['store', 'destroy']);

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['title', 'content', 'user_id', 'category_id'];

    function categories() {

        return $this->belongsTo(Category::class);
    }


    function addCategories( array $categories ) {

        $this->categories()->attach( $categories );
    }

}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Comment;
use App\Post;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('posts.create', compact( 'categories' ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $fields = $request->validate([
            'title' => 'required|max:50',
            'content' => 'required',
            'categories' => 'required'
        ]);


        $post = Post::create( [
            'title' => $fields['title'],
            'content' => $fields['content'],
            'user_id' => Auth::user()->id,
            'category_id' => $fields['categories']['0']
        ] );

        //$post->addCategories( $fields['categories']);

        return redirect(route('home'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        $post = Post::find($post->id);

        $user = User::find($post->user_id);

        $comments = Comment::all();

        $comments = $comments->where('post_id', $post->id);

        return view('posts.show', compact('post', 'user', 'comments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $post = Post::find($post->id);

        $categories = Category::all();
        return view('posts.edit', compact('post', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        /*if (Auth::user()->id != $post->id)
            return back();*/

        $fields = $request->validate([
            'title' => 'required|max:50',
            'content' => 'required',
            'categories' => 'required'
        ]);

        $post->update( [
            'title' => $fields['title'],
            'content' => $fields['content'],
            'category_id' => $fields['categories']['0']] );

        return redirect(route('posts.show', $post));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post $post
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Post $post)
    {
        //if (Auth::user()->id != $post->id)
          //  return back();

        $post->delete();
        return redirect(route('home'));
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <h2>Add Posts: </h2>
        <form action="{{route('posts.store')}}" method="post">
            {{-- Protected field CSRF --}}
            @csrf
            <label>
                <span>Title : </span>
                <input type="text" name="title" value="{{old('title')}}">
            </label><br>
            <label>
                <span>Content : </span>
                <textarea name="content">{{old('content')}}</textarea>
            </label><br>

            <hr>

            <select name="categories">
                @foreach ($categories as $category)
                            <option value="{{$category->id}}">{{ $category->label }}</option>
                @endforeach
            </select> <br><br>

            <input type="submit" value="Submit">
        </form>

    </div>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')


@section('content')


    <h1>Edit an Posts.</h1>

    <form action="{{route('posts.update', $post)}}" method="post">

        @csrf

        @method('PUT')
        <label>
            <span>Title : </span>
            <input type="text" name="title" value="{{ old('title') ?: $post->title}}">
        </label><br>
        <label>
            <span>Content : </span>
            <textarea name="content">{{ old('content') ?: $post->content}}</textarea>
        </label><br>

            <select name="categories">

                        @foreach ($categories as $category)
                            <option value="{{$category->id}}"
                            @if ($category->id == $post->category_id)
                                <?php echo "selected"; ?>
                            @endif>{{ $category->label }}</option>
                        @endforeach

            </select> <br><br>
        <input class="btn btn-success" type="submit" value="Update">
    </form>
@endsection

resources/views/posts/index.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: stage
 * Date: 2019-02-18
 * Time: 11:42
 */

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('title', 'Details post ' . $post->id)

@section('header')
@endsection

@section('content')
<div class="container">
    <h3>{{$post->title}}</h3>
    <div class="card">


        <div class="card-body">

            <p>{{$post->content}}</p>
        </div>
    </div>


    <span><i>Author: {{$user->name}} </i></span><br>

    @auth()
        @if (Auth::user()->id == $post->user_id)
            <button class="btn btn-outline-success"><a href="{{route('posts.edit', $post)}}">Edit post</a></button>

            <form action="{{route('posts.destroy', $post)}}" method="post">
                @csrf
                @method('DELETE')
                <input class="btn btn-danger" type="submit" value="Delete post">
            </form>
        @endif
    @endauth

    <hr>
    <hr>
    <div>
        @if (!empty($comments))

            @foreach ($comments as $comment)
                <div class="card">
                    <div class="card-body">

                        <p class="flex-wrap">{{ \App\Comment::smiley($comment->content) }}</p>
                    </div>
            @auth()
                @if (Auth::user()->id == $comment->user_id)
                    <form method="POST" action="{{ route('comments.destroy', [ $post->id, $comment->id ]) }}">
                        @csrf
                        @method('DELETE')
                        <input type="submit" value="Delete">
                    </form>
                @endif
            @endauth
                    <span><i>by {{$comment->user->name}}</i></span>
                </div>

            <hr>

            @endforeach
        @endif
    </div>

    @auth()
        <h4>Respond:</h4>

        <form method="POST" action="{{ route('comments.store', $post->id)}}">
            @csrf
            <textarea name="content"></textarea> <br>
            <input type="submit" value="Respond now !">
        </form>
    @endauth
</div>
@endsection