routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index')->name('home');

Route::resource('categories', 'CategoryController')
    ->parameters([
        'category' =>'[0-9]+'
    ]);

Route::resource('posts', 'PostController')
    ->parameters([
        'post' =>'[0-9]+'
    ]);

/*Route::resource('comments', 'CommentController')->onlu
    ->parameters([
        'comment' =>'[0-9]+'
    ]);*/

Route::resource('/posts/{post}/comments', 'CommentController')->only(['store', 'destroy']);

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['label'];

    function posts() {
        return $this->belongsToMany( Post::class );
    }
    function getPosts() {

        /*return DB::table('albums')
            ->join('photos', 'albums.id', '=', 'photos.album_id')
            ->select('photos.title', 'albums.title AS album_title', 'albums.slug AS album_slug')
            ->get();*/
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CategoryController extends Controller
{

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $field = $request->validate([
            'label' => 'required|max:50'
        ]);

        $category = Category::create( $field );

        return redirect(route('home', $category));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        $posts = Post::all();
        $posts = $posts->where('category_id', $category->id);

        return view('categories.show', compact('posts', 'category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <h2>Add Category:</h2>

        <form action="{{route('categories.store')}}" method="POST">

            @csrf

            @csrf
            <label>
                <span>Label category : </span>
                <input type="text" name="label" value="{{old('title')}}" placeholder="Label...">
            </label><br>

            <input type="submit" value="Create">

        </form>
    </div>
@endsection

resources/views/categories/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <h2>All Post in {{$category->label}}: </h2>
            <div class="col-md-8 flex-div">
                @foreach ($posts as $post)

                    <div class="card" style="width: 18rem;">
                        <div class="card-body div-body">
                            <h5 class="card-title">{{$post->title}}</h5>
                            <a href="{{route('posts.show', $post->id)}}" class="card-link"><button type="button" class="btn btn-outline-success">Show detail</button></a>
                        </div>
                    </div>
                @endforeach

            </div>
        </div>
    </div>
@endsection